// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200813074826_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Number");

                    b.Property<string>("RoomName");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new { RoomId = 1, Number = 1, RoomName = "Room1" },
                        new { RoomId = 2, Number = 2, RoomName = "Room2" }
                    );
                });

            modelBuilder.Entity("Domain.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthOfDate");

                    b.Property<int>("RoomId");

                    b.Property<string>("StudentName");

                    b.HasKey("StudentId");

                    b.HasIndex("RoomId");

                    b.ToTable("Students");

                    b.HasData(
                        new { StudentId = 1, BirthOfDate = new DateTime(2020, 8, 13, 14, 48, 24, 776, DateTimeKind.Local), RoomId = 1, StudentName = "Student1" },
                        new { StudentId = 2, BirthOfDate = new DateTime(1998, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), RoomId = 2, StudentName = "Student2" },
                        new { StudentId = 3, BirthOfDate = new DateTime(1998, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), RoomId = 2, StudentName = "Student3" }
                    );
                });

            modelBuilder.Entity("Domain.Student", b =>
                {
                    b.HasOne("Domain.Room", "Room")
                        .WithMany("Students")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
